name: Build Cross-Platform Apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 수동 실행 가능

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build Windows executable
      run: |
        pyinstaller --onefile --windowed --name=BlogPhotoDownloader-Windows --strip --clean --additional-hooks-dir=. --collect-all selenium --collect-all webdriver_manager --collect-submodules selenium --collect-submodules webdriver_manager --exclude-module=matplotlib --exclude-module=numpy --exclude-module=pandas --exclude-module=scipy --exclude-module=PIL --exclude-module=pytest --exclude-module=IPython --exclude-module=jupyter blog_photo_down.py
          
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: BlogPhotoDownloader-Windows
        path: dist/BlogPhotoDownloader-Windows.exe
        retention-days: 30

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build macOS app
      run: |
        pyinstaller --onedir --windowed --name=BlogPhotoDownloader-macOS \
          --strip --clean --additional-hooks-dir=. \
          --collect-all selenium --collect-all webdriver_manager \
          --collect-submodules selenium --collect-submodules webdriver_manager \
          --exclude-module=matplotlib --exclude-module=numpy \
          --exclude-module=pandas --exclude-module=scipy \
          --exclude-module=PIL --exclude-module=pytest \
          --exclude-module=IPython --exclude-module=jupyter \
          blog_photo_down.py
          
    - name: Create macOS zip
      run: |
        cd dist
        zip -r BlogPhotoDownloader-macOS.zip BlogPhotoDownloader-macOS.app
        
    - name: Upload macOS app
      uses: actions/upload-artifact@v4
      with:
        name: BlogPhotoDownloader-macOS
        path: dist/BlogPhotoDownloader-macOS.zip
        retention-days: 30

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build Linux executable
      run: |
        pyinstaller --onefile --windowed --name=BlogPhotoDownloader-Linux \
          --strip --clean --additional-hooks-dir=. \
          --collect-all selenium --collect-all webdriver_manager \
          --collect-submodules selenium --collect-submodules webdriver_manager \
          --exclude-module=matplotlib --exclude-module=numpy \
          --exclude-module=pandas --exclude-module=scipy \
          --exclude-module=PIL --exclude-module=pytest \
          --exclude-module=IPython --exclude-module=jupyter \
          blog_photo_down.py
          
    - name: Upload Linux executable
      uses: actions/upload-artifact@v4
      with:
        name: BlogPhotoDownloader-Linux
        path: dist/BlogPhotoDownloader-Linux
        retention-days: 30 